name: Azure Functions

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs: 
          
    Build_Functions:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET v5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Setup .NET Core v3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
        
      - name: Restore NuGet 
        run: |
          dotnet restore **/**.sln
          
      - name: Build Android App
        run: |                    
          dotnet build ./Src/UITestSampleApp.Functions -c Release
